config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :relation_types
    resources :products, only: [:index, :show] do
      get :related, on: :member
      resources :relations
    end
  end
end

app/models/spree/calculator/related_product_discount.rb
module Spree
  class Calculator::RelatedProductDiscount < Spree::Calculator
    preference :item_total_threshold, :decimal, default: 5

    def self.description
      Spree.t(:related_product_discount)
    end

    def compute(object)
      if object.is_a?(Array)
        return if object.empty?
        order = object.first.order
      else
        order = object
      end

      return unless eligible?(order)
      total = order.line_items.inject(0) do |total, line_item|
        relations =  Spree::Relation.find(:all, conditions: ["discount_amount <> 0.0 AND relatable_type = ? AND relatable_id = ?", "Spree::Product", line_item.variant.product.id])
        discount_applies_to = relations.map {|rel| rel.related_to.master }

        order.line_items.each do |li|
          if discount_applies_to.include? li.variant
            discount = relations.detect {|rel| rel.related_to.master == li.variant}.discount_amount

            total += if li.quantity < line_item.quantity
              (discount * li.quantity)
            else
              (discount * line_item.quantity)
            end
          end
        end

        total
      end

      total == 0 ? nil : total
    end

    def eligible?(order)
      order.line_items.any? { |line_item| Spree::Relation.exists?(["discount_amount <> 0.0 AND relatable_type = ? AND relatable_id = ?", "Spree::Product", line_item.variant.product.id])}
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :relations, as: :relatable

  # Returns all the Spree::RelationType's which apply_to this class.
  def self.relation_types
    Spree::RelationType.find_all_by_applies_to(self.to_s, order: :name)
  end

  # The AREL Relations that will be used to filter the resultant items.
  #
  # By default this will remove any items which are deleted, or not yet available.
  #
  # You can override this method to fine tune the filter. For example,
  # to only return Spree::Product's with more than 2 items in stock, you could
  # do the following:
  #
  #   def self.relation_filter
  #     set = super
  #     set.where('spree_products.count_on_hand >= 2')
  #   end
  #
  # This could also feasibly be overridden to sort the result in a
  # particular order, or restrict the number of items returned.
  def self.relation_filter
    where('spree_products.deleted_at' => nil).where('spree_products.available_on IS NOT NULL').where('spree_products.available_on <= ?', Time.now)
  end

  # Decides if there is a relevant Spree::RelationType related to this class
  # which should be returned for this method.
  #
  # If so, it calls relations_for_relation_type. Otherwise it passes
  # it up the inheritance chain.
  def method_missing(method, *args)
    # Fix for Ruby 1.9
    raise NoMethodError if method == :to_ary

    relation_type = nil
    begin
      relation_type =  self.class.relation_types.detect { |rt| rt.name.downcase.gsub(" ", "_").pluralize == method.to_s.downcase }
    rescue ActiveRecord::StatementInvalid => error
      # This exception is throw if the relation_types table does not exist.
      # And this method is getting invoked during the execution of a migration
      # from another extension when both are used in a project.
      relation_type = nil
    end

    if relation_type.nil?
      super
    else
      relations_for_relation_type(relation_type)
    end
  end

  private

  # Returns all the Products that are related to this record for the given RelationType.
  #
  # Uses the Relations to find all the related items, and then filters
  # them using +Product.relation_filter+ to remove unwanted items.
  def relations_for_relation_type(relation_type)
    # Find all the relations that belong to us for this RelationType
    related_ids = relations.where(relation_type_id: relation_type.id).select(:related_to_id).collect(&:related_to_id)

    # Construct a query for all these records
    result = self.class.where(id: related_ids)

    # Merge in the relation_filter if it's available
    result = result.merge(self.class.relation_filter.scoped) if relation_filter

    result
  end

  # Simple accessor for the class-level relation_filter.
  # Could feasibly be overloaded to filter results relative to this
  # record (eg. only higher priced items)
  def relation_filter
    self.class.relation_filter
  end
end

app/models/spree/relation.rb
class Spree::Relation < ActiveRecord::Base
  belongs_to :relation_type
  belongs_to :relatable, polymorphic: true
  belongs_to :related_to, polymorphic: true

  validates :relation_type, :relatable, :related_to, presence: true

  attr_accessible :related_to, :relation_type, :relatable, :related_to_id, :discount_amount, :relation_type_id, :related_to_type
end

app/models/spree/relation_type.rb
class Spree::RelationType < ActiveRecord::Base
  has_many :relations, dependent: :destroy

  attr_accessible :name, :applies_to, :description

  validates :name, :applies_to, presence: true
  validates :name, uniqueness: true
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  def related
    load_resource
    @relation_types = Spree::Product.relation_types
  end
end

app/controllers/spree/admin/relation_types_controller.rb
module Spree
  module Admin
    class RelationTypesController < ResourceController
    end
  end
end

app/controllers/spree/admin/relations_controller.rb
module Spree
  module Admin
    class RelationsController < BaseController
      before_filter :load_data, only: [:create, :destroy]

      respond_to :js, :html

      def create
        @relation = Spree::Relation.new
        product = Spree::Product.find(params[:product_id])
        @relation.relatable = product
        @relation.relation_type = Spree::RelationType.find_by_id(params[:relation][:relation_type_id])
        @relation.related_to = Spree::Variant.find(params[:relation][:related_to_id]).product

        if @relation.save
          redirect_to(action: 'index', notice: "The relation is successfully created.")
        else
          redirect_to(action: 'new')
        end
      end

      def update
        @relation = Spree::Relation.find(params[:id])
        @relation.update_attribute :discount_amount, params[:relation][:discount_amount] || 0

        redirect_to(related_admin_product_url(@relation.relatable))
      end

      def destroy
        @relation = Spree::Relation.find(params[:id])
        @relation.destroy

        respond_to do |format|
          format.js  { render_js_for_destroy }
        end
      end

      private

      def load_data
        @product = Spree::Product.find_by_permalink(params[:product_id])
      end

      def model_class
        Spree::Relation
      end
    end
  end
end

app/views/spree/admin/products/_related_products.html.erb
<li<%== ' class="active"' if current == "Related Products" %>>
  <%= link_to_with_icon 'icon-sitemap', Spree.t(:related_products), related_admin_product_url(@product) %>
</li>

app/views/spree/admin/products/_related_products_table.html.erb
<table class="index">
  <thead>
    <tr>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:discount_amount) %></th>
      <th><%= Spree.t(:type) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% product.relations.each do |relation| %>
      <tr id="<%= dom_id relation %>">
        <td><%= link_to relation.related_to.name, relation.related_to %></td>
        <td><%= form_for(relation, url: admin_product_relation_path(relation.relatable, relation)) do |f| %>
           <%= f.text_field :discount_amount, size: 4 %> &nbsp; <%= f.submit Spree.t(:update) %> <% end %></td>
        <td><%= relation.relation_type.name %></td>
        <td width="70px">
          <%= link_to_delete relation, {url: admin_product_relation_url(relation.relatable, relation)} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/related.html.erb
<%= render 'spree/admin/shared/product_sub_menu' %>
<%= render 'spree/admin/shared/product_tabs', current: 'Related Products' %>
<%= render "spree/admin/variants/autocomplete", formats: :js %>

<%= csrf_meta_tag %>

<% if @relation_types.empty? %>
  <%= Spree.t(:no_relation_types) %>
<% else %>
  <div id="add-line-item">
    <fieldset>
      <legend><%= Spree.t(:add_related_product) %></legend>
      <div class="columns four">
        <%= label_tag :add_variant_name, Spree.t(:name_or_sku) %>
        <%= hidden_field_tag :add_variant_name, "", class: 'variant_autocomplete fullwidth' %>
      </div>
      <div class="columns three">
        <%= label_tag :add_type, Spree.t(:type) %><br/>
        <%= select_tag :add_type, options_for_select(@relation_types.map{|rt| [rt.name, rt.id]}), class: 'select2' %>
      </div>
      <div class="columns three">
        <%= label_tag :add_discount, Spree.t(:discount_amount) %>
        <%= text_field_tag :add_discount, 0.0, style: 'margin: 0pt; padding: 4px; font-size: 1.5em; width: 98%;'  %>
      </div>
      <div class="columns one">
        <label style="visibility: hidden;">&nbsp;</label>
        <%= link_to text_for_button_link(Spree.t(:add), icon: 'add'),
          admin_product_relations_url(@product),
          {id: 'add_related_product', class: 'button', 'data-update' => 'products-table-wrapper'} %>
      </div>
    </fieldset>
  </div>

  <div id="products-table-wrapper">
    <%= render 'related_products_table', product: @product %>
  </div>

  <%= content_for :head do %>
    <script>
      var expand_variants = false;

      $(document).on('click','#add_related_product', function() {
        if ($('#add_variant_name').val() == '') { return false; }
        update_target = $(this).prop('data-update');

        $.ajax({
          dataType: 'script',
          url: this.href,
          type: 'POST',
          data: {
            'relation[related_to_type]' : 'Product',
            'relation[related_to_id]': $('#add_variant_name').val(),
            'relation[relation_type_id]': $('#add_type').val(),
            'relation[discount_amount]' : $('#add_discount').val()
          }
        });
        return false;
      });

      $(function () {
        $('#add_variant_name.variant_autocomplete').variantAutocomplete();
      });
    </script>
  <% end %>
<% end %>

app/views/spree/admin/relation_types/_form.html.erb
<div data-hook="admin_relation_type_form_fields">
  <%= f.field_container :name do %>
    <%= f.label :name, Spree.t(:name) %><br />
    <%= f.text_field :name, class: 'fullwidth title' %>
    <%= error_message_on :relation_type, :name %>
  <% end %>

  <%= f.field_container :applies_to do %>
    <%= f.label :applies_to, Spree.t(:applies_to) %><br />
    <%= f.text_field :applies_to, value: f.object.nil? ? 'Spree::Product' : f.object.applies_to, class: 'fullwidth title' %>
    <%= error_message_on :relation_type, :applies_to %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description, Spree.t(:description) %><br />
    <%= f.text_area :description, {cols: 60, rows: 2, class: 'fullwidth'} %>
    <%= error_message_on :relation_type, :description %>
  <% end %>
</div>

app/views/spree/admin/relation_types/edit.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<div data-hook="admin_relation_type_edit_form_header">
  <h1><%= Spree.t(:editing_relation_type) %></h1>

  <%= render 'spree/shared/error_messages', target: @relation_type %>
</div>

<div data-hook="admin_relation_type_edit_form">
  <%= form_for(@relation_type, url: object_url, html: { method: :put }) do |f| %>
    <%= render 'form', f: f %>

    <div data-hook="admin_relation_type_edit_form_buttons">
      <%= render 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/relation_types/index.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<div class="toolbar">
  <ul class="actions header-action-links inline-menu">
    <li>
      <%= button_link_to Spree.t(:new_relation_type), new_object_url, icon: 'add'  %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= Spree.t(:relation_types) %></h1>

<table class="index">
  <thead>
    <tr data-hook="admin_relation_types_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:applies_to) %></th>
      <th><%= Spree.t(:description) %></th>
      <th data-hook="admin_relation_types_index_header_actions">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @relation_types.each do |relation_type| %>
      <tr id="<%= dom_id relation_type %>" data-hook="admin_relation_types_index_rows">
        <td><%= relation_type.name %></td>
        <td><%= relation_type.applies_to %></td>
        <td><%= relation_type.description %></td>
        <td width="140px" data-hook="admin_relation_types_index_row_actions">
          <%= link_to_edit relation_type %> &nbsp;
          <%= link_to_delete relation_type %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/relation_types/new.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<div data-hook="admin_relation_type_new_form_header">
  <h1><%= Spree.t(:new_relation_type) %></h1>

  <%= render 'spree/shared/error_messages', target: @relation_type %>
</div>

<div data-hook="admin_relation_type_new_form" >
  <%= form_for(:relation_type, url: collection_url) do |f| %>
    <%= render 'form', f: f %>

    <div data-hook="admin_relation_type_new_form_buttons">
      <%= render 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/relations/create.js.erb
$("#products-table-wrapper").html('<%= escape_javascript(render "spree/admin/products/related_products_table", product: @product ) %>');
$('#add_product_name').val('');
$('#add_variant_id').val('');
$('#add_quantity').val(1);

app/views/spree/admin/relations/destroy.js.erb
$("#products-table-wrapper").html('<%= escape_javascript(render "spree/admin/products/related_products_table", product: @product ) %>');